# Use a Node.js image as a base
FROM node:16

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your application code
COPY . .

# Expose the port your backend runs on
EXPOSE 3003

# Start the server
CMD ["npm", "run", "dev"]
